alias 'dc'='docker-compose'
alias 'dcu'='docker-compose up'
alias 'dcd'='docker-compose down'
alias 'dcp'='docker-compose ps'
alias 'dcb'='docker-compose build --parallel'
alias 'dcr'='docker-compose run --rm'
alias 'dce'='docker-compose exec'
alias 'grin'='grep -rin'
alias 'vim'='nvim'
alias 'tunnelpsql'='ssh -v -N -L 5432:localhost:5432 root@criat'
alias 'lastbranches'='git branch --sort=committerdate --color | tail -n 5'
alias 's'='jump sling-server'
alias 'dualscreen'='xrandr --output DP1 --mode 2560x1440 --right-of eDP1'
alias 'cb'='git commit -m "Backup"'
alias 'pr'='hub pull-request'
alias 'ppr'='hub pull-request -b prefab'
alias 'gcp'='git checkout prefab-staging'
alias 'more'='git commit --allow-empty-message -m ""'
alias 'chromium-socks'='chromium-browser --proxy-server="socks5://localhost:7777"'
alias 'gap'='git add -p'
alias 'c'='jump core'
alias 'i'='jump i'
